shop/main/urls.py
from django.urls import path

from . import views
from .views import ProductListView, ProductPhoneView, ProductDeleteView

app_name = 'main'

urlpatterns = [
    # http://127.0.0.1:8000
    path('', ProductListView.as_view(), name='index'),
    # http://127.0.0.1:8000/id
    path('<int:pk>/', ProductPhoneView.as_view(), name='phones'),

    # http://127.0.0.1:8000/addphone
    path('addphone/', views.AddPhones, name='addphone'),

    # http://127.0.0.1:8000/updatephone/*id
    path('updatephone/<int:id>/', views.UpdatePhone, name='UpdatePhone'),

    # http://127.0.0.1:8000/deletephone/*id
    path('deletephone/<int:id>/', views.DeletePhone, name='DeletePhone'),

    path('success/',views.PaymentSuccessView.as_view(), name='success'),

    path('failed/', views.PaymentFailedView.as_view(), name='failed'),

    path('api/checkout-session/<int:id>/', views.create_checkout_session, name='api_checkout_session'),


]

shop/shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    # http://127.0.0.1:8000/admin
    path('admin/', admin.site.urls),
    # http://127.0.0.1:8000/
    path('', include('main.urls', namespace='main')),
    # http://127.0.0.1:8000/users
    path('users/', include('users.urls', namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/',LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('seller-profile/<int:id>/', views.seller_profile, name='seller_profile'),
]

shop/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default='1')
    name = models.CharField(max_length=100, unique=True, null=False, blank=False, verbose_name= 'Наименование')
    price = models.IntegerField(verbose_name='Цена')
    description = models.TextField(max_length=300, verbose_name='Описание')
    image = models.ImageField( blank=True, upload_to='images')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name


class OrderPhone(models.Model):
    customer_username = models.CharField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    amount = models.IntegerField()
    stripe_payment = models.CharField(max_length=200)
    has_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

shop/main/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseNotFound, JsonResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import DeleteView
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import json
import stripe

from .models import Product, OrderPhone


def index(request):
    page_obj = products = Product.objects.all()

    item_name = request.GET.get('search')
    if item_name != '' and item_name is not None:
        page_obj = products.filter(name__icontains=item_name)

    paginator = Paginator(page_obj, 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'main/index.html', context)


class ProductListView(ListView):
    model = Product
    template_name = 'main/index.html'
    context_object_name = 'products'
    paginate_by = 1


# def id_Product(request, id):
#     phone = Product.objects.get(id=id)
#     context = {
#         'phone': phone
#     }
#     return render(request, 'main/phones.html', context)


class ProductPhoneView(DetailView):
    model = Product
    template_name = 'main/phones.html'
    context_object_name = 'phone'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super(ProductPhoneView, self).get_context_data(**kwargs)
        context['stripe_publishable_key'] = settings.STRIPE_PUBLISHABLE_KEY
        return context


@login_required
def AddPhones(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        description = request.POST.get('description')
        image = request.FILES.get('image')
        seller = request.user
        phone = Product(name=name, price=price, description=description, image=image, seller=seller)
        phone.save()
    return render(request, 'main/addphone.html')


@login_required
def UpdatePhone(request, id):
    phone = Product.objects.get(id=id)
    if request.method == 'POST':
        phone.name = request.POST.get('name')
        phone.price = request.POST.get('price')
        phone.description = request.POST.get('description')
        phone.image = request.FILES.get('upload')
        phone.save()
        return redirect('/')

    context = {
        'phone': phone
    }
    return render(request, 'main/updatephone.html', context)


@login_required
def DeletePhone(request, id):
    phone = Product.objects.get(id=id)
    if request.method == 'POST':
        phone.delete()
        return redirect('/')
    context = {
        'phone': phone
    }
    return render(request, 'main/deletephone.html', context)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('main:index')


@csrf_exempt
def create_checkout_session(request, id):
    product = get_object_or_404(Product, pk=id)
    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session = stripe.checkout.Session.create(
        customer_email=request.user.email,
        payment_method_types=['card'],
        line_items=[
            {
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                        'name': product.name,
                    },
                    'unit_amount': int(product.price * 100),
                },
                'quantity': 1,
            }
        ],
        mode="payment",
        success_url=request.build_absolute_uri(reverse('main:success'))
                    + '?session_id+{CHECKOUT_SESSION_ID}',
        cancel_url=request.build_absolute_uri(reverse('main:failed')),
    )
    order = OrderPhone()
    order.customer_username = request.user.username
    order.product = product
    order.stripe_payment_intent = checkout_session['payment_intent']
    order.amount = int(product.price * 100)
    order.save()
    return JsonResponse({'sessionId': checkout_session.id})


class PaymentSuccessView(TemplateView):
    template_name = 'main/payment_success.html'

    def get(self, request, *args, **kwargs):
        session_id = request.GET.get('session_id')
        if session_id is None:
            return HttpResponseNotFound
        session = stripe.checkout.Session.retrieve(session_id)
        stripe.api_key = settings.STRIPE_SECRET_KEY
        order = get_object_or_404(OrderPhone, stripe_payment_intent=session.session.payment_intent)
        order.has_paid = True
        order.save()
        return render(request, self.template_name)


class PaymentFailedView(TemplateView):
    template_name = 'main/payment_failed.html'

shop/main/templates/main/addphone.html
{% extends 'main/base.html' %}

{% block content %}
<div class="ml-[200px]">
  <h1 class="text-2xl m-10 font-bold text-green-600"> Add New Item Below</h1>
  <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="post" enctype="multipart/form-data">
  {% csrf_token %}
    <div>
      <label class="block text-gray-700 text-md font-bold mb-2" for="name"> Item Name</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Name..." name="name" id="name">
      <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price"> Item Price</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Price..." name="price" id="price">
      <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description"> Item Description</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Description..." name="description" id="description">
      <input class="block mt-4" type="file" accept="images/*" name="upload" id="upload">
      <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Phone">Add Item</button>
    </div>
  </form>
</div>

{% endblock %}

shop/main/templates/main/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'main/styles.css' %}">
  <title>Document</title>
</head>
<body>

{% include 'main/navbar.html' %}

  {% block content %}
  {% endblock %}
</body>
</html>

shop/main/templates/main/deletephone.html
{% extends 'main/base.html' %}

{% block content %}
  <h1 class="text-2xl m-10 font-bold"> Delete Phone</h1>
  <form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="post">
  {% csrf_token %}
  <div class="mb-4">
    <label class="block text-gray text-sm font mb-2" for=""> Are you sure want to delete this phone?</label>
    <label class="block text-gray text-sm font mb-2" for=""> {{ phone.name }}</label>
    <img class="w-70 h-70" src="{{ phone.image.url }}" alt="">
  </div>
  <input class="bg-red-500 text-white px-5 py-2" type="submit" value="Confirm">
  <a class="button bg-green-500 text-white px-5 py-3" href="{% url 'main:index' %}">Cancel</a>
</form>
{% endblock %}

shop/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load humanize %}

{% block content %}
<main class="mt-10 mx-auto max-w-7xl px-4 sm: mt-12 sm: px-6 md: mt-16 lg: mt-20 lg:px-8 xl:mt-28">
  <div class="sm:text-center lg:text-left">
    <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
      <span class="block xl:inline"> Эсклюзивные Товары</span>
      <span class="block xl:inline text-green-500">По Низким Ценам</span>
    </h1>
    <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md: text-xl lg:mx-0"> Вы можете заказать доставку из любой точки мира </p>
  </div>

  <div class="mt-5 -10 justify-center">
    <h2>Search</h2>
    <form action="" method="get">
      <input type="text" name="search" id="">
    </form>
  </div>

<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-3">
  {% for product in products %}
      <a href="{% url 'main:phones' product.id %}">
        <div class="rounded overflow-hidden shadow-lg">
          <img class="w-full h-[400px]" src="{{ product.image.url }}" alt="">
          <div class="px-6 py-4">
            <p class="font-bold text-xl mb-2"> {{ product.name }}</p>
            <p class="font-bold text-xl text-green-500 mb-2"> $ {{ product.price | intcomma }}</p>
            <p class="font-bold text-xl text-indigo-300 mb-2"> by: {{ product.seller }}</p>
            <p class="text-gray-700 text-base "> {{ product.description }} </p>
          </div>
        </div>
      </a>
  {% endfor %}
</div>
<div>

  <span>
    {% if page_obj.has_previous %}
      <a href="?page=1">First</a>
      <a href="?page={{ page_obj.previous_page_number }}">Previous</a>

    {% endif %}
  </span>
  <span>
    {{ page_obj }}
  </span>

  <span>
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">Next</a>
      <a href="?page={{ page_obj.paginator.num_pages}}">Last</a>
    {% endif %} 
  </span>

</div>
</main>





{% endblock %}

shop/main/templates/main/navbar.html
{% load static %}

<nav class="bg-white shadow-lg">
    <div class="max-w-6xl mx-auto px-4">
      <div class="flex justify-between">
        <div class="flex space-x-7">
          <div class="">
            <a href="{% url 'main:index' %}" class="flex items-center px-2 py-4">
            <img class="h-8 w-8" src="{% static 'main/images/logo.png' %}" alt="logo">
            <span class="text-gray-500 font-semibold text-xl">Pro Shop</span>
            </a>
          </div>
          <div class="items-center flex space-x-1">
            <a href="{% url 'main:index' %}" class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
            <a href="{% url 'main:addphone' %}" class="py-4 px-2 text-gray-500 font-semibold">Add Phone</a>
            <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
            {% if user.is_authenticated %}
              <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
              <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
            {% else %}
              <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
            {% endif %} 
          </div>
        </div>
      </div>
    </div>
  </nav>

shop/main/templates/main/payment_failed.html
{% extends 'main/base.html' %}

{% block content %}
  <h1>Payment failed</h1>
{% endblock %}

shop/main/templates/main/payment_success.html
{% extends 'main/base.html' %}

{% block content %}
  <h1> You have successfully paid</h1>
{% endblock %}

shop/main/templates/main/phones.html
{% extends 'main/base.html' %}
{% load  humanize %}

{% block content %}
  <div class="flex p-10 w-full h-200">
    <img class="w-1/3 " src="{{ phone.image.url }}" alt="PhonePhoto">
    <div class="w-2/3 text-xl ml-10 mt-5">
      <p class="mt-5"> {{ phone.name }}</p>
      <p class="mt-5 text-green-500"> $ {{ phone.price | intcomma }}</p>
      <p class="mt-5 text-gray-600"> {{ phone.description }}</p>
      <p class="mt-5 text-gray-600"><a href="{% url 'users:seller_profile' phone.seller.id %}">@{{ phone.seller }}</a></p>
      <p class="mt-5 text-gray-600"> {{ phone.seller.profile.contact_number }}</p>
      <button class="bg-green-600 text-white mt-[50px]"><a href="{% url 'main:UpdatePhone' phone.id %}">Update Item</a></button>
      <button class="bg-red-600 text-white mt-[50px]"><a href="{% url 'main:DeletePhone' phone.id %}">Delete Item</a></button>
      <button class="bg-green-600 text-white mt-[50px]" id="checkout">Checkout</button>

    </div>
  </div>
  <script src="https://js.stripe.com/v3/"></script>
  <script type="text/javascript">
      var stripe = Stripe('{{ stripe_publishable_key }}')
      var checkoutButton = document.getElementById('checkout')
      checkoutButton.addEventListener('click', function (){
          fetch("{% url 'main:api_checkout_session' phone.id %}",{method: 'POST',})
              .then(function(response){
                  return response.json()
              })
              .then(function(session){
                  return stripe.redirectToCheckout({sessionId: session.sessionId})
              })
              .then(function(result){
                  if (result.error){
                      alert(result.error.message)
                  }
              })
              .catch(function (error){
                  console.log('Error', error);
              })
      })
  </script>
{% endblock %}

shop/main/templates/main/product_confirm_delete.html
<form method="post">
  {% csrf_token %}
  <p> Do you want to delete {{ object }}? </p>
  {{ form }}
  <input type="submit" value="Delete">
</form>

shop/main/templates/main/updatephone.html
{% extends 'main/base.html' %}

{% block content %}
<div class="ml-[200px]">
  <h1 class="text-2xl m-10 font-bold text-green-600"> Update Item</h1>
  <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="post" enctype="multipart/form-data">
  {% csrf_token %}
    <div>
      <label class="block text-gray-700 text-md font-bold mb-2" for="name"> Item Name</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ phone.name }}" type="text" placeholder="Name..." name="name" id="name">
      <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price"> Item Price</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700"  value="{{ phone.price }}" type="text" placeholder="Price..." name="price" id="price">
      <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description"> Item Description</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ phone.description }}" type="text" placeholder="Description..." name="description" id="description">
      <img class="w-20 h-20" src="{{ phone.image.url }}" alt="">
      <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
      <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Phone">Update Item</button>
    </div>
  </form>
</div>

{% endblock %}